/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UsersApiTests
    {
        private UsersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UsersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UsersApi
            //Assert.IsInstanceOfType(typeof(UsersApi), instance, "instance is a UsersApi");
        }

        /// <summary>
        /// Test UsersAuthenticatePost
        /// </summary>
        [Test]
        public void UsersAuthenticatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthenticateDto body = null;
            //var response = instance.UsersAuthenticatePost(body);
            //Assert.IsInstanceOf<CurrentUserDto> (response, "response is CurrentUserDto");
        }
        /// <summary>
        /// Test UsersIdGet
        /// </summary>
        [Test]
        public void UsersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.UsersIdGet(id);
            //Assert.IsInstanceOf<User> (response, "response is User");
        }
        /// <summary>
        /// Test UsersUsosAuthDataGet
        /// </summary>
        [Test]
        public void UsersUsosAuthDataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UsersUsosAuthDataGet();
            //Assert.IsInstanceOf<UsosAuthDto> (response, "response is UsosAuthDto");
        }
        /// <summary>
        /// Test UsersUsosPinAuthPost
        /// </summary>
        [Test]
        public void UsersUsosPinAuthPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UsosAuthDto body = null;
            //var response = instance.UsersUsosPinAuthPost(body);
            //Assert.IsInstanceOf<CurrentUserDto> (response, "response is CurrentUserDto");
        }
    }

}
