/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// QuestionAnswerDto
    /// </summary>
    [DataContract]
        public partial class QuestionAnswerDto :  IEquatable<QuestionAnswerDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuestionAnswerDto" /> class.
        /// </summary>
        /// <param name="respondentId">respondentId.</param>
        /// <param name="respondent">respondent.</param>
        /// <param name="value">value.</param>
        public QuestionAnswerDto(int? respondentId = default(int?), string respondent = default(string), Object value = default(Object))
        {
            this.RespondentId = respondentId;
            this.Respondent = respondent;
            this.Value = value;
        }
        
        /// <summary>
        /// Gets or Sets RespondentId
        /// </summary>
        [DataMember(Name="respondentId", EmitDefaultValue=false)]
        public int? RespondentId { get; set; }

        /// <summary>
        /// Gets or Sets Respondent
        /// </summary>
        [DataMember(Name="respondent", EmitDefaultValue=false)]
        public string Respondent { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuestionAnswerDto {\n");
            sb.Append("  RespondentId: ").Append(RespondentId).Append("\n");
            sb.Append("  Respondent: ").Append(Respondent).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuestionAnswerDto);
        }

        /// <summary>
        /// Returns true if QuestionAnswerDto instances are equal
        /// </summary>
        /// <param name="input">Instance of QuestionAnswerDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuestionAnswerDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RespondentId == input.RespondentId ||
                    (this.RespondentId != null &&
                    this.RespondentId.Equals(input.RespondentId))
                ) && 
                (
                    this.Respondent == input.Respondent ||
                    (this.Respondent != null &&
                    this.Respondent.Equals(input.Respondent))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RespondentId != null)
                    hashCode = hashCode * 59 + this.RespondentId.GetHashCode();
                if (this.Respondent != null)
                    hashCode = hashCode * 59 + this.Respondent.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
