/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnswerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnswerDtoTests
    {
        // TODO uncomment below to declare an instance variable for AnswerDto
        //private AnswerDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnswerDto
            //instance = new AnswerDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnswerDto
        /// </summary>
        [Test]
        public void AnswerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnswerDto
            //Assert.IsInstanceOfType<AnswerDto> (instance, "variable 'instance' is a AnswerDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'QuestionText'
        /// </summary>
        [Test]
        public void QuestionTextTest()
        {
            // TODO unit test for the property 'QuestionText'
        }
        /// <summary>
        /// Test the property 'QuestionType'
        /// </summary>
        [Test]
        public void QuestionTypeTest()
        {
            // TODO unit test for the property 'QuestionType'
        }
        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Test]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }

    }

}
