/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CourseParticipant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CourseParticipantTests
    {
        // TODO uncomment below to declare an instance variable for CourseParticipant
        //private CourseParticipant instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CourseParticipant
            //instance = new CourseParticipant();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CourseParticipant
        /// </summary>
        [Test]
        public void CourseParticipantInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CourseParticipant
            //Assert.IsInstanceOfType<CourseParticipant> (instance, "variable 'instance' is a CourseParticipant");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ParticipantId'
        /// </summary>
        [Test]
        public void ParticipantIdTest()
        {
            // TODO unit test for the property 'ParticipantId'
        }
        /// <summary>
        /// Test the property 'Participant'
        /// </summary>
        [Test]
        public void ParticipantTest()
        {
            // TODO unit test for the property 'Participant'
        }
        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Test]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }
        /// <summary>
        /// Test the property 'Course'
        /// </summary>
        [Test]
        public void CourseTest()
        {
            // TODO unit test for the property 'Course'
        }

    }

}
