/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CourseLecturer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CourseLecturerTests
    {
        // TODO uncomment below to declare an instance variable for CourseLecturer
        //private CourseLecturer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CourseLecturer
            //instance = new CourseLecturer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CourseLecturer
        /// </summary>
        [Test]
        public void CourseLecturerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CourseLecturer
            //Assert.IsInstanceOfType<CourseLecturer> (instance, "variable 'instance' is a CourseLecturer");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LecturerId'
        /// </summary>
        [Test]
        public void LecturerIdTest()
        {
            // TODO unit test for the property 'LecturerId'
        }
        /// <summary>
        /// Test the property 'Lecturer'
        /// </summary>
        [Test]
        public void LecturerTest()
        {
            // TODO unit test for the property 'Lecturer'
        }
        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Test]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }
        /// <summary>
        /// Test the property 'Course'
        /// </summary>
        [Test]
        public void CourseTest()
        {
            // TODO unit test for the property 'Course'
        }

    }

}
