/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CourseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CourseDtoTests
    {
        // TODO uncomment below to declare an instance variable for CourseDto
        //private CourseDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CourseDto
            //instance = new CourseDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CourseDto
        /// </summary>
        [Test]
        public void CourseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CourseDto
            //Assert.IsInstanceOfType<CourseDto> (instance, "variable 'instance' is a CourseDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SemesterId'
        /// </summary>
        [Test]
        public void SemesterIdTest()
        {
            // TODO unit test for the property 'SemesterId'
        }
        /// <summary>
        /// Test the property 'SemesterName'
        /// </summary>
        [Test]
        public void SemesterNameTest()
        {
            // TODO unit test for the property 'SemesterName'
        }
        /// <summary>
        /// Test the property 'LeaderId'
        /// </summary>
        [Test]
        public void LeaderIdTest()
        {
            // TODO unit test for the property 'LeaderId'
        }

    }

}
