/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuestionAnswerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuestionAnswerDtoTests
    {
        // TODO uncomment below to declare an instance variable for QuestionAnswerDto
        //private QuestionAnswerDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuestionAnswerDto
            //instance = new QuestionAnswerDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuestionAnswerDto
        /// </summary>
        [Test]
        public void QuestionAnswerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuestionAnswerDto
            //Assert.IsInstanceOfType<QuestionAnswerDto> (instance, "variable 'instance' is a QuestionAnswerDto");
        }


        /// <summary>
        /// Test the property 'RespondentId'
        /// </summary>
        [Test]
        public void RespondentIdTest()
        {
            // TODO unit test for the property 'RespondentId'
        }
        /// <summary>
        /// Test the property 'Respondent'
        /// </summary>
        [Test]
        public void RespondentTest()
        {
            // TODO unit test for the property 'Respondent'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
