/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuestionResultsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuestionResultsDtoTests
    {
        // TODO uncomment below to declare an instance variable for QuestionResultsDto
        //private QuestionResultsDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuestionResultsDto
            //instance = new QuestionResultsDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuestionResultsDto
        /// </summary>
        [Test]
        public void QuestionResultsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuestionResultsDto
            //Assert.IsInstanceOfType<QuestionResultsDto> (instance, "variable 'instance' is a QuestionResultsDto");
        }


        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Test]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }
        /// <summary>
        /// Test the property 'QuestionText'
        /// </summary>
        [Test]
        public void QuestionTextTest()
        {
            // TODO unit test for the property 'QuestionText'
        }
        /// <summary>
        /// Test the property 'QuestionType'
        /// </summary>
        [Test]
        public void QuestionTypeTest()
        {
            // TODO unit test for the property 'QuestionType'
        }
        /// <summary>
        /// Test the property 'QuestionAnswers'
        /// </summary>
        [Test]
        public void QuestionAnswersTest()
        {
            // TODO unit test for the property 'QuestionAnswers'
        }
        /// <summary>
        /// Test the property 'AnswerPercentages'
        /// </summary>
        [Test]
        public void AnswerPercentagesTest()
        {
            // TODO unit test for the property 'AnswerPercentages'
        }
        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Test]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }

    }

}
