/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Statistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatisticsTests
    {
        // TODO uncomment below to declare an instance variable for Statistics
        //private Statistics instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Statistics
            //instance = new Statistics();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Statistics
        /// </summary>
        [Test]
        public void StatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Statistics
            //Assert.IsInstanceOfType<Statistics> (instance, "variable 'instance' is a Statistics");
        }


        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Test]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Test]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'Median'
        /// </summary>
        [Test]
        public void MedianTest()
        {
            // TODO unit test for the property 'Median'
        }
        /// <summary>
        /// Test the property 'Variance'
        /// </summary>
        [Test]
        public void VarianceTest()
        {
            // TODO unit test for the property 'Variance'
        }
        /// <summary>
        /// Test the property 'StandardDeviation'
        /// </summary>
        [Test]
        public void StandardDeviationTest()
        {
            // TODO unit test for the property 'StandardDeviation'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

    }

}
