/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurveyResultsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurveyResultsDtoTests
    {
        // TODO uncomment below to declare an instance variable for SurveyResultsDto
        //private SurveyResultsDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurveyResultsDto
            //instance = new SurveyResultsDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurveyResultsDto
        /// </summary>
        [Test]
        public void SurveyResultsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurveyResultsDto
            //Assert.IsInstanceOfType<SurveyResultsDto> (instance, "variable 'instance' is a SurveyResultsDto");
        }


        /// <summary>
        /// Test the property 'SurveyId'
        /// </summary>
        [Test]
        public void SurveyIdTest()
        {
            // TODO unit test for the property 'SurveyId'
        }
        /// <summary>
        /// Test the property 'SurveyName'
        /// </summary>
        [Test]
        public void SurveyNameTest()
        {
            // TODO unit test for the property 'SurveyName'
        }
        /// <summary>
        /// Test the property 'Anonymous'
        /// </summary>
        [Test]
        public void AnonymousTest()
        {
            // TODO unit test for the property 'Anonymous'
        }
        /// <summary>
        /// Test the property 'QuestionResults'
        /// </summary>
        [Test]
        public void QuestionResultsTest()
        {
            // TODO unit test for the property 'QuestionResults'
        }

    }

}
