/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurveyListItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurveyListItemDtoTests
    {
        // TODO uncomment below to declare an instance variable for SurveyListItemDto
        //private SurveyListItemDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurveyListItemDto
            //instance = new SurveyListItemDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurveyListItemDto
        /// </summary>
        [Test]
        public void SurveyListItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurveyListItemDto
            //Assert.IsInstanceOfType<SurveyListItemDto> (instance, "variable 'instance' is a SurveyListItemDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'IsTemplate'
        /// </summary>
        [Test]
        public void IsTemplateTest()
        {
            // TODO unit test for the property 'IsTemplate'
        }
        /// <summary>
        /// Test the property 'Anonymous'
        /// </summary>
        [Test]
        public void AnonymousTest()
        {
            // TODO unit test for the property 'Anonymous'
        }
        /// <summary>
        /// Test the property 'CourseName'
        /// </summary>
        [Test]
        public void CourseNameTest()
        {
            // TODO unit test for the property 'CourseName'
        }
        /// <summary>
        /// Test the property 'CreatorName'
        /// </summary>
        [Test]
        public void CreatorNameTest()
        {
            // TODO unit test for the property 'CreatorName'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
