/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurveyDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurveyDtoTests
    {
        // TODO uncomment below to declare an instance variable for SurveyDto
        //private SurveyDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurveyDto
            //instance = new SurveyDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurveyDto
        /// </summary>
        [Test]
        public void SurveyDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurveyDto
            //Assert.IsInstanceOfType<SurveyDto> (instance, "variable 'instance' is a SurveyDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Test]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }
        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Test]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }
        /// <summary>
        /// Test the property 'Questions'
        /// </summary>
        [Test]
        public void QuestionsTest()
        {
            // TODO unit test for the property 'Questions'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'CourseName'
        /// </summary>
        [Test]
        public void CourseNameTest()
        {
            // TODO unit test for the property 'CourseName'
        }
        /// <summary>
        /// Test the property 'CreatorName'
        /// </summary>
        [Test]
        public void CreatorNameTest()
        {
            // TODO unit test for the property 'CreatorName'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
