/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurveyResponseDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurveyResponseDetailsDtoTests
    {
        // TODO uncomment below to declare an instance variable for SurveyResponseDetailsDto
        //private SurveyResponseDetailsDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurveyResponseDetailsDto
            //instance = new SurveyResponseDetailsDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurveyResponseDetailsDto
        /// </summary>
        [Test]
        public void SurveyResponseDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurveyResponseDetailsDto
            //Assert.IsInstanceOfType<SurveyResponseDetailsDto> (instance, "variable 'instance' is a SurveyResponseDetailsDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RespondentId'
        /// </summary>
        [Test]
        public void RespondentIdTest()
        {
            // TODO unit test for the property 'RespondentId'
        }
        /// <summary>
        /// Test the property 'Answers'
        /// </summary>
        [Test]
        public void AnswersTest()
        {
            // TODO unit test for the property 'Answers'
        }
        /// <summary>
        /// Test the property 'SurveyName'
        /// </summary>
        [Test]
        public void SurveyNameTest()
        {
            // TODO unit test for the property 'SurveyName'
        }
        /// <summary>
        /// Test the property 'Respondent'
        /// </summary>
        [Test]
        public void RespondentTest()
        {
            // TODO unit test for the property 'Respondent'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'CourseName'
        /// </summary>
        [Test]
        public void CourseNameTest()
        {
            // TODO unit test for the property 'CourseName'
        }
        /// <summary>
        /// Test the property 'SurveyId'
        /// </summary>
        [Test]
        public void SurveyIdTest()
        {
            // TODO unit test for the property 'SurveyId'
        }

    }

}
