/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SurveyResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SurveyResponseDtoTests
    {
        // TODO uncomment below to declare an instance variable for SurveyResponseDto
        //private SurveyResponseDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SurveyResponseDto
            //instance = new SurveyResponseDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SurveyResponseDto
        /// </summary>
        [Test]
        public void SurveyResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SurveyResponseDto
            //Assert.IsInstanceOfType<SurveyResponseDto> (instance, "variable 'instance' is a SurveyResponseDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RespondentId'
        /// </summary>
        [Test]
        public void RespondentIdTest()
        {
            // TODO unit test for the property 'RespondentId'
        }
        /// <summary>
        /// Test the property 'Answers'
        /// </summary>
        [Test]
        public void AnswersTest()
        {
            // TODO unit test for the property 'Answers'
        }
        /// <summary>
        /// Test the property 'SurveyId'
        /// </summary>
        [Test]
        public void SurveyIdTest()
        {
            // TODO unit test for the property 'SurveyId'
        }

    }

}
