/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UsosAuthDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UsosAuthDtoTests
    {
        // TODO uncomment below to declare an instance variable for UsosAuthDto
        //private UsosAuthDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UsosAuthDto
            //instance = new UsosAuthDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsosAuthDto
        /// </summary>
        [Test]
        public void UsosAuthDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UsosAuthDto
            //Assert.IsInstanceOfType<UsosAuthDto> (instance, "variable 'instance' is a UsosAuthDto");
        }


        /// <summary>
        /// Test the property 'UsosAuthUrl'
        /// </summary>
        [Test]
        public void UsosAuthUrlTest()
        {
            // TODO unit test for the property 'UsosAuthUrl'
        }
        /// <summary>
        /// Test the property 'RequestToken'
        /// </summary>
        [Test]
        public void RequestTokenTest()
        {
            // TODO unit test for the property 'RequestToken'
        }
        /// <summary>
        /// Test the property 'TokenSecret'
        /// </summary>
        [Test]
        public void TokenSecretTest()
        {
            // TODO unit test for the property 'TokenSecret'
        }
        /// <summary>
        /// Test the property 'OAuthVerifier'
        /// </summary>
        [Test]
        public void OAuthVerifierTest()
        {
            // TODO unit test for the property 'OAuthVerifier'
        }

    }

}
