/* 
 * Student survey system API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValidationConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValidationConfigTests
    {
        // TODO uncomment below to declare an instance variable for ValidationConfig
        //private ValidationConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidationConfig
            //instance = new ValidationConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidationConfig
        /// </summary>
        [Test]
        public void ValidationConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValidationConfig
            //Assert.IsInstanceOfType<ValidationConfig> (instance, "variable 'instance' is a ValidationConfig");
        }


        /// <summary>
        /// Test the property 'MinNumericValue'
        /// </summary>
        [Test]
        public void MinNumericValueTest()
        {
            // TODO unit test for the property 'MinNumericValue'
        }
        /// <summary>
        /// Test the property 'MaxNumericValue'
        /// </summary>
        [Test]
        public void MaxNumericValueTest()
        {
            // TODO unit test for the property 'MaxNumericValue'
        }
        /// <summary>
        /// Test the property 'Integer'
        /// </summary>
        [Test]
        public void IntegerTest()
        {
            // TODO unit test for the property 'Integer'
        }
        /// <summary>
        /// Test the property 'MinDateValue'
        /// </summary>
        [Test]
        public void MinDateValueTest()
        {
            // TODO unit test for the property 'MinDateValue'
        }
        /// <summary>
        /// Test the property 'MaxDateValue'
        /// </summary>
        [Test]
        public void MaxDateValueTest()
        {
            // TODO unit test for the property 'MaxDateValue'
        }
        /// <summary>
        /// Test the property 'Regex'
        /// </summary>
        [Test]
        public void RegexTest()
        {
            // TODO unit test for the property 'Regex'
        }

    }

}
