name: Build

on: [push, pull_request]

jobs:
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android and iOS
      run: |
        nuget restore
        msbuild StudentSurveySystem.MobileClient.sln /verbosity:normal /t:Rebuild /p:Configuration=Debug